controller_manager:
  ros__parameters:
    update_rate: 50
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    # Controller for each joint, modify names as per your URDF
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        # Add all your robot's joint names
      state_publish_rate: 50
      command_interfaces:
        - position
      allow_partial_joints_goal: true

    # Define interfaces for direct control
    velocity_controllers:
      joint_1_velocity_controller:
        type: effort_controllers/JointVelocityController
        joint: joint_1
      joint_2_velocity_controller:
        type: effort_controllers/JointVelocityController
        joint: joint_2
      # Repeat for all other joints

    position_controllers:
      joint_1_position_controller:
        type: position_controllers/JointPositionController
        joint: joint_1
      joint_2_position_controller:
        type: position_controllers/JointPositionController
        joint: joint_2
      # Repeat for all other joints

spawner:
  ros__parameters:
    joint_state_controller:
      package: controller_manager
      executable: spawner
      arguments: ["joint_state_controller"]

    joint_trajectory_controller:
      package: controller_manager
      executable: spawner
      arguments: ["joint_trajectory_controller"]

